using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 

namespace ICATXML
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("icat", Namespace = "", IsNullable = false)]
    public partial class Icat
    {

        private Study[] studyField;

        private string versionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("study")]
        public Study[] study
        {
            get
            {
                return this.studyField;
            }
            set
            {
                this.studyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Study
    {

        private string nameField;

        private string purposeField;

        private Status statusField;

        private bool statusFieldSpecified;

        private string related_materialField;

        private System.DateTime study_creation_dateField;

        private bool study_creation_dateFieldSpecified;

        private string study_managerField;

        private Investigation[] investigationField;

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string purpose
        {
            get
            {
                return this.purposeField;
            }
            set
            {
                this.purposeField = value;
            }
        }

        /// <remarks/>
        public Status status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string related_material
        {
            get
            {
                return this.related_materialField;
            }
            set
            {
                this.related_materialField = value;
            }
        }

        /// <remarks/>
        public System.DateTime study_creation_date
        {
            get
            {
                return this.study_creation_dateField;
            }
            set
            {
                this.study_creation_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool study_creation_dateSpecified
        {
            get
            {
                return this.study_creation_dateFieldSpecified;
            }
            set
            {
                this.study_creation_dateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string study_manager
        {
            get
            {
                return this.study_managerField;
            }
            set
            {
                this.study_managerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("investigation")]
        public Investigation[] investigation
        {
            get
            {
                return this.investigationField;
            }
            set
            {
                this.investigationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    public enum Status
    {

        /// <remarks/>
        ONGOING,

        /// <remarks/>
        CLOSED,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Investigation
    {

        private string inv_numberField;

        private string visit_idField;

        private string[] instrumentField;

        private string titleField;

        private Investigator[] investigatorField;

        private string inv_abstractField;

        private string inv_typeField;

        private string prev_inv_numberField;

        private string bcat_inv_strField;

        private string grant_idField;

        private string facility_cycleField;

        private Keyword[] keywordField;

        private Topic[] topicField;

        private Publication[] publicationField;

        private Sample[] sampleField;

        private Dataset[] datasetField;

        private bool trustedField;

        public Investigation()
        {
            this.trustedField = true;
        }

        /// <remarks/>
        public string inv_number
        {
            get
            {
                return this.inv_numberField;
            }
            set
            {
                this.inv_numberField = value;
            }
        }

        /// <remarks/>
        public string visit_id
        {
            get
            {
                return this.visit_idField;
            }
            set
            {
                this.visit_idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("instrument")]
        public string[] instrument
        {
            get
            {
                return this.instrumentField;
            }
            set
            {
                this.instrumentField = value;
            }
        }

        /// <remarks/>
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("investigator")]
        public Investigator[] investigator
        {
            get
            {
                return this.investigatorField;
            }
            set
            {
                this.investigatorField = value;
            }
        }

        /// <remarks/>
        public string inv_abstract
        {
            get
            {
                return this.inv_abstractField;
            }
            set
            {
                this.inv_abstractField = value;
            }
        }

        /// <remarks/>
        public string inv_type
        {
            get
            {
                return this.inv_typeField;
            }
            set
            {
                this.inv_typeField = value;
            }
        }

        /// <remarks/>
        public string prev_inv_number
        {
            get
            {
                return this.prev_inv_numberField;
            }
            set
            {
                this.prev_inv_numberField = value;
            }
        }

        /// <remarks/>
        public string bcat_inv_str
        {
            get
            {
                return this.bcat_inv_strField;
            }
            set
            {
                this.bcat_inv_strField = value;
            }
        }

        /// <remarks/>
        public string grant_id
        {
            get
            {
                return this.grant_idField;
            }
            set
            {
                this.grant_idField = value;
            }
        }

        /// <remarks/>
        public string facility_cycle
        {
            get
            {
                return this.facility_cycleField;
            }
            set
            {
                this.facility_cycleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("keyword")]
        public Keyword[] keyword
        {
            get
            {
                return this.keywordField;
            }
            set
            {
                this.keywordField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("topic")]
        public Topic[] topic
        {
            get
            {
                return this.topicField;
            }
            set
            {
                this.topicField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("publication")]
        public Publication[] publication
        {
            get
            {
                return this.publicationField;
            }
            set
            {
                this.publicationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sample")]
        public Sample[] sample
        {
            get
            {
                return this.sampleField;
            }
            set
            {
                this.sampleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dataset")]
        public Dataset[] dataset
        {
            get
            {
                return this.datasetField;
            }
            set
            {
                this.datasetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool trusted
        {
            get
            {
                return this.trustedField;
            }
            set
            {
                this.trustedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Investigator
    {

        private string user_idField;

        private string roleField;

        private string privilegeField;

        private string titleField;

        private string initialsField;

        private string first_nameField;

        private string middle_nameField;

        private string last_nameField;

        private string affiliationField;

        private string affiliation_idField;

        /// <remarks/>
        public string user_id
        {
            get
            {
                return this.user_idField;
            }
            set
            {
                this.user_idField = value;
            }
        }

        /// <remarks/>
        public string role
        {
            get
            {
                return this.roleField;
            }
            set
            {
                this.roleField = value;
            }
        }

        /// <remarks/>
        public string privilege
        {
            get
            {
                return this.privilegeField;
            }
            set
            {
                this.privilegeField = value;
            }
        }

        /// <remarks/>
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        public string initials
        {
            get
            {
                return this.initialsField;
            }
            set
            {
                this.initialsField = value;
            }
        }

        /// <remarks/>
        public string first_name
        {
            get
            {
                return this.first_nameField;
            }
            set
            {
                this.first_nameField = value;
            }
        }

        /// <remarks/>
        public string middle_name
        {
            get
            {
                return this.middle_nameField;
            }
            set
            {
                this.middle_nameField = value;
            }
        }

        /// <remarks/>
        public string last_name
        {
            get
            {
                return this.last_nameField;
            }
            set
            {
                this.last_nameField = value;
            }
        }

        /// <remarks/>
        public string affiliation
        {
            get
            {
                return this.affiliationField;
            }
            set
            {
                this.affiliationField = value;
            }
        }

        /// <remarks/>
        public string affiliation_id
        {
            get
            {
                return this.affiliation_idField;
            }
            set
            {
                this.affiliation_idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Datafile
    {

        private string nameField;

        private string locationField;

        private string descriptionField;

        private string datafile_versionField;

        private string datafile_version_commentField;

        private string datafile_formatField;

        private string datafile_format_versionField;

        private System.DateTime datafile_create_timeField;

        private System.DateTime datafile_modify_timeField;

        private string file_sizeField;

        private string commandField;

        private string checksumField;

        private string signatureField;

        private Parameter[] parameterField;

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        /// <remarks/>
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string datafile_version
        {
            get
            {
                return this.datafile_versionField;
            }
            set
            {
                this.datafile_versionField = value;
            }
        }

        /// <remarks/>
        public string datafile_version_comment
        {
            get
            {
                return this.datafile_version_commentField;
            }
            set
            {
                this.datafile_version_commentField = value;
            }
        }

        /// <remarks/>
        public string datafile_format
        {
            get
            {
                return this.datafile_formatField;
            }
            set
            {
                this.datafile_formatField = value;
            }
        }

        /// <remarks/>
        public string datafile_format_version
        {
            get
            {
                return this.datafile_format_versionField;
            }
            set
            {
                this.datafile_format_versionField = value;
            }
        }

        /// <remarks/>
        public System.DateTime datafile_create_time
        {
            get
            {
                return this.datafile_create_timeField;
            }
            set
            {
                this.datafile_create_timeField = value;
            }
        }

        /// <remarks/>
        public System.DateTime datafile_modify_time
        {
            get
            {
                return this.datafile_modify_timeField;
            }
            set
            {
                this.datafile_modify_timeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string file_size
        {
            get
            {
                return this.file_sizeField;
            }
            set
            {
                this.file_sizeField = value;
            }
        }

        /// <remarks/>
        public string command
        {
            get
            {
                return this.commandField;
            }
            set
            {
                this.commandField = value;
            }
        }

        /// <remarks/>
        public string checksum
        {
            get
            {
                return this.checksumField;
            }
            set
            {
                this.checksumField = value;
            }
        }

        /// <remarks/>
        public string signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parameter")]
        public Parameter[] parameter
        {
            get
            {
                return this.parameterField;
            }
            set
            {
                this.parameterField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Parameter
    {

        private string nameField;

        private object itemField;

        private string unitsField;

        private string range_topField;

        private string range_bottomField;

        private string errorField;

        private string descriptionField;

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("numeric_value", typeof(double))]
        [System.Xml.Serialization.XmlElementAttribute("string_value", typeof(string))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        public string units
        {
            get
            {
                return this.unitsField;
            }
            set
            {
                this.unitsField = value;
            }
        }

        /// <remarks/>
        public string range_top
        {
            get
            {
                return this.range_topField;
            }
            set
            {
                this.range_topField = value;
            }
        }

        /// <remarks/>
        public string range_bottom
        {
            get
            {
                return this.range_bottomField;
            }
            set
            {
                this.range_bottomField = value;
            }
        }

        /// <remarks/>
        public string error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }

        /// <remarks/>
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Dataset
    {

        private string nameField;

        private string dataset_typeField;

        private string dataset_statusField;

        private string descriptionField;

        private Sample sampleField;

        private Datafile[] datafileField;

        private Parameter[] parameterField;

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string dataset_type
        {
            get
            {
                return this.dataset_typeField;
            }
            set
            {
                this.dataset_typeField = value;
            }
        }

        /// <remarks/>
        public string dataset_status
        {
            get
            {
                return this.dataset_statusField;
            }
            set
            {
                this.dataset_statusField = value;
            }
        }

        /// <remarks/>
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public Sample sample
        {
            get
            {
                return this.sampleField;
            }
            set
            {
                this.sampleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("datafile")]
        public Datafile[] datafile
        {
            get
            {
                return this.datafileField;
            }
            set
            {
                this.datafileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parameter")]
        public Parameter[] parameter
        {
            get
            {
                return this.parameterField;
            }
            set
            {
                this.parameterField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Sample
    {

        private string nameField;

        private string instanceField;

        private string chemical_formulaField;

        private string safety_informationField;

        private Parameter[] parameterField;

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string instance
        {
            get
            {
                return this.instanceField;
            }
            set
            {
                this.instanceField = value;
            }
        }

        /// <remarks/>
        public string chemical_formula
        {
            get
            {
                return this.chemical_formulaField;
            }
            set
            {
                this.chemical_formulaField = value;
            }
        }

        /// <remarks/>
        public string safety_information
        {
            get
            {
                return this.safety_informationField;
            }
            set
            {
                this.safety_informationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parameter")]
        public Parameter[] parameter
        {
            get
            {
                return this.parameterField;
            }
            set
            {
                this.parameterField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Publication
    {

        private string full_referenceField;

        private string urlField;

        private string repository_idField;

        private string repositoryField;

        /// <remarks/>
        public string full_reference
        {
            get
            {
                return this.full_referenceField;
            }
            set
            {
                this.full_referenceField = value;
            }
        }

        /// <remarks/>
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        /// <remarks/>
        public string repository_id
        {
            get
            {
                return this.repository_idField;
            }
            set
            {
                this.repository_idField = value;
            }
        }

        /// <remarks/>
        public string repository
        {
            get
            {
                return this.repositoryField;
            }
            set
            {
                this.repositoryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Topic
    {

        private string nameField;

        private string topic_levelField;

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "nonNegativeInteger")]
        public string topic_level
        {
            get
            {
                return this.topic_levelField;
            }
            set
            {
                this.topic_levelField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Keyword
    {

        private string nameField;

        /// <remarks/>
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
}

