//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICAT4IngestLibrary.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uows")]
        public string ICATAuthnComp {
            get {
                return ((string)(this["ICATAuthnComp"]));
            }
            set {
                this["ICATAuthnComp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 1000, -1000, 12345, 99999, 999999")]
        public string CalibrationRBs {
            get {
                return ((string)(this["CalibrationRBs"]));
            }
            set {
                this["CalibrationRBs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ICAT Success")]
        public string Success_Queue {
            get {
                return ((string)(this["Success_Queue"]));
            }
            set {
                this["Success_Queue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string post_Error_Ingest {
            get {
                return ((string)(this["post_Error_Ingest"]));
            }
            set {
                this["post_Error_Ingest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string ICAT_Wait {
            get {
                return ((string)(this["ICAT_Wait"]));
            }
            set {
                this["ICAT_Wait"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ICAT")]
        public string ICAT_Queue {
            get {
                return ((string)(this["ICAT_Queue"]));
            }
            set {
                this["ICAT_Queue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("activemq:failover:(localhost:61616)")]
        public string URL {
            get {
                return ((string)(this["URL"]));
            }
            set {
                this["URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Long ICAT")]
        public string Long_Queue {
            get {
                return ((string)(this["Long_Queue"]));
            }
            set {
                this["Long_Queue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pre ICAT Error Queue")]
        public string Error_Queue {
            get {
                return ((string)(this["Error_Queue"]));
            }
            set {
                this["Error_Queue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("isisdata@stfc.ac.uk")]
        public string ICATUsername {
            get {
                return ((string)(this["ICATUsername"]));
            }
            set {
                this["ICATUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gPRa$\"yBgcw45!PQYF")]
        public string ICATPassword {
            get {
                return ((string)(this["ICATPassword"]));
            }
            set {
                this["ICATPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ActiveIngest\\IngestExternalXmls\\Instruments.xml")]
        public string InstrumentsXMLFile {
            get {
                return ((string)(this["InstrumentsXMLFile"]));
            }
            set {
                this["InstrumentsXMLFile"] = value;
            }
        }
    }
}
